### ISSUE TITLE
[ Feature ] Modules in Terraform for Dynamic Updates

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/mordor#15]
https://github.com/Cyb3rWard0g/mordor/issues/14

**Comment by jsecurity101** [comment]
@Cyb3rWard0g per our conversation on Issue #14, dynamic updates are possible.

**Comment by Cyb3rWard0g** [comment]
I know it is possible @jsecurity101 . I am opening an official issue to track the feature requested. I already linked the issue 14 in the comments of this issue when it was opened. I will leave it open as a reminder and to track any work on it.

**Comment by jsecurity101** [comment]
Hey @Cyb3rWard0g I am adding this into the `Project` section!

**Comment by Cyb3rWard0g** [comment]
Taking care of it via other cloud templates.
