### ISSUE TITLE
[Cloud] AWS Shire  - Define main components

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/mordor#3]
**Deployment type:**

- Pre-Built AMI's 
- Terraform
- AWS

This will allow end users to utilize least amount of resources. 

**Deliverable:**
- Documentation of each component and why they were selected
- Design

**Comment by jsecurity101** [comment]
HELK Pre-Built AMI is configured and in testing states of Terraform

**Comment by jsecurity101** [comment]
HELK tested and completed. Documentation on HELK AMI is done.

**Comment by jsecurity101** [comment]
Project is up and working. Validated Terraform build script. Project can be found here: https://github.com/jsecurity101/mordor 

Updated scripts and Terraform script. 

Script will load 7 pre-built ami's. Login can be done on Apache Guacamole from the "Empire" box.

**Comment by jsecurity101** [comment]
Everything is ready for review: https://github.com/Cyb3rWard0g/mordor/tree/mordor_aws/environment/shire/aws/terraform

**Comment by Cyb3rWard0g** [comment]
let me know if this can be closed or not. thank you @jsecurity101
