### ISSUE TITLE
[Cloud] AWS Shire - Active Directory Scripts Validation

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/mordor#4]
Tasks:
- Validate that current scripts https://github.com/Cyb3rWard0g/mordor/tree/master/environment/shire/scripts deploy the same environment presented in the docs: https://mordor.readthedocs.io/en/latest/network_shire.html
- Test GPOs and WEF subscriptions deployment locally
- Add additional documentation if needed.

**Comment by jsecurity101** [comment]
DHCP script will not work, it will break the AWS connection. Going with building the VPC inside of Terraform script

**Comment by jsecurity101** [comment]
Created an ImportGPOs.ps1 to import GPOs from the GPOBackup. 

configure-wec.ps1 had a syntax issue in one of the HKLM's. Updated this and works. 

I didn't use DHCP or the forest script, I created the forest manually.
